# Generated by Django 5.2.4 on 2025-08-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
